services:
  graph-solver-backend:
    container_name: graph-solver-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_DEV_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_DEV_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
